### PR TITLE
V22.1.0 + Complete refactor

### PR DESCRIPTION
**Pull request by jmarrec**
Complete refactor of the C++ code to eliminate global state, use constexpr, avoid gotos

This builds upon #91, but I didn't want to put it there because this is untested yet.

### CODE REVIEW

**Comment by antoine-galataud** [comment]
@jmarrec thanks for the refactoring, I have to test that.

**Comment by jmarrec** [comment]
https://github.com/jmarrec/EnergyPlus/releases/tag/v22.1.0-rl-testbed-refactor

**Comment by jmarrec** [comment]
FYI in 536db89 I made some extra refactoring, which will correspond to this new release: https://github.com/jmarrec/EnergyPlus/releases/tag/v22.1.0-rl-testbed-refactor-extra

In that one:
* I cleaned up the API (correct types for params, return types)
* set up error codes from Erl in case something went wrong
* and added ExtCtrlObs/ExtCtrlAct to the C and Python API
    * The usefulness of that part is quite limited since you can already achieve everything you're doing without doing any patching via this API with the current actuators / sensors. That would require moving to Python (or... C... but who would) instead of using Erl (EMS). So if you do move to a Python EMS code instead of Erl, then the ExtCtrl stuff becomes kinda pointless. But hey, why not right?

**Comment by antoine-galataud** [comment]
tested the main loop and it works fine. I didn't test new error codes handling and integration in C/Python API, but shouldn't be a problem to merge as is and see if it's functional and useful later.

**Pull request merged**
